[book]
authors = ["MJ PC Lab"]
language = "zh-CN"
title = "Web二进制媒体编程"

[build]
build-dir = "dist"


[output.html]
git-repository-url = "https://github.com/mjpclab/web-binary-media-programming"
print.enable = false
playground.copyable = false
preferred-dark-theme = "ayu"
